INSERT INTO products
  (name,description,price,weight,category,origin,flavor,image_url,tea_type,water_color,brewing_guide,storage_guide,discount_percent,discount_amount,stock,sold_count,is_hot)
SELECT seed.*
FROM (VALUES
  ('Bánh đậu xanh ít ngọt','Bánh mềm, vị bùi dịu và ít ngọt, phù hợp dùng lót dạ khi thưởng trà.',45000,'Hộp 180g','Đồ ăn kèm trà','Việt Nam','Bùi nhẹ, ngọt thanh','/images/companions/banh-dau-xanh-thanh-chuong.jpg','Đồ ăn nhẹ','Không áp dụng','Mở gói và dùng trực tiếp cùng trà. Dùng lượng vừa phải.','Đậy kín sau khi mở, để nơi khô ráo và dùng theo hạn trên bao bì.',5,0,40,0,FALSE),
  ('Hạt điều rang nguyên vị','Hạt điều giòn bùi, không tẩm vị đậm, tiện dùng cùng trà trong buổi sáng hoặc giữa giờ.',79000,'Hũ 200g','Đồ ăn kèm trà','Việt Nam','Giòn bùi, nguyên vị','/images/companions/hat-dieu-thanh-chuong.jpg','Đồ ăn nhẹ','Không áp dụng','Mở gói và dùng trực tiếp cùng trà. Dùng lượng vừa phải.','Đậy kín sau khi mở, để nơi khô ráo và dùng theo hạn trên bao bì.',5,0,35,0,FALSE),
  ('Thanh ngũ cốc hạt dinh dưỡng','Thanh ngũ cốc nhỏ gọn với các loại hạt, thích hợp cho một bữa ăn nhẹ trước khi uống trà.',65000,'Hộp 6 thanh','Đồ ăn kèm trà','Việt Nam','Thơm hạt, ngọt vừa','/images/companions/thanh-ngu-coc-thanh-chuong.jpg','Đồ ăn nhẹ','Không áp dụng','Mở gói và dùng trực tiếp cùng trà. Dùng lượng vừa phải.','Đậy kín sau khi mở, để nơi khô ráo và dùng theo hạn trên bao bì.',5,0,30,0,FALSE),
  ('Mứt gừng lát mật ong','Gừng lát thơm ấm, vị ngọt dịu, dùng từng miếng nhỏ để cân bằng vị trà.',55000,'Túi 150g','Đồ ăn kèm trà','Nghệ An, Việt Nam','Thơm ấm, ngọt dịu','/images/companions/mut-gung-thanh-chuong.jpg','Đồ ăn nhẹ','Không áp dụng','Mở gói và dùng trực tiếp cùng trà. Dùng lượng vừa phải.','Đậy kín sau khi mở, để nơi khô ráo và dùng theo hạn trên bao bì.',5,0,30,0,FALSE)
) AS seed(name,description,price,weight,category,origin,flavor,image_url,tea_type,water_color,brewing_guide,storage_guide,discount_percent,discount_amount,stock,sold_count,is_hot)
WHERE NOT EXISTS (SELECT 1 FROM products existing WHERE LOWER(existing.name)=LOWER(seed.name));
